spring.application.name=bookstore-pos-digital-library

server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false

harvard.api.base-url=${HARVARD_API_BASE_URL:https://api.lib.harvard.edu/v2/items.json}
harvard.api.key=${HARVARD_API_KEY:}

receipt.output-directory=${RECEIPT_OUTPUT_DIR:receipts}
member.discount-percentage=${MEMBER_DISCOUNT_PERCENTAGE:10}
