spring.application.name=bookstore-pos-digital-library

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/digilib_fpj?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false

harvard.api.base-url=https://api.lib.harvard.edu/v2/items.json
harvard.api.key=

receipt.output-directory=receipts
member.discount-percentage=10
